server:
  port: 8084
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountmanagementservice
    username: root 
    password: root 
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  
  application:
    name: Account-Management-Service
    

  config:
    import: configserver:http://localhost:8086
    
#eureka:
#  instance:
#    prefer-ip-address: true
#  client: 
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8083/eureka     
#      
      